services:
  web:
    build: .
    volumes:
      - .:/app:cached
      - ./data:/app/data
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: src/app.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command: flask run --host=0.0.0.0 --port=5000
